- project:
    name: openstack/virtualbmc
    check:
      jobs:
        - virtualbmc-tempest-dsvm-ironic-pxe_ipmitool-src
    gate:
      jobs:
        - virtualbmc-tempest-dsvm-ironic-pxe_ipmitool-src
